name: Super Poderoso Accions

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  CheckSintaxis:
    runs-on: [self-hosted]
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - name: Validar Sintaxis
        run: for archivo in $(find . | grep php); do  php -l $archivo || exit 1; done

  CheckearSiHayVar_dump:
    runs-on: [self-hosted]
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - name: Validar en appAlumno Var_dump
        run: grep -q -r var_dump appAlumno/* && exit 1 || true

      - name: Validar en appDocente Var_dump
        run: grep -q -r var_dump appDocente/* && exit 1 || true

      - name: Validar en appAdmin Var_dump
        run: grep -q -r var_dump appAdmin/* && exit 1 || true

  CheckearSiHayPrint_r:
    runs-on: [self-hosted]
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - name: Validar en appAlumno Print_r
        run: grep -q -r print_r appAlumno/* && exit 1 || true

      - name: Validar en appDocente Print_r
        run: grep -q -r print_r appDocente/* && exit 1 || true

      - name: Validar en appAdmin Print_r
        run: grep -q -r print_r appAdmin/* && exit 1 || true

  RunUnitTestsAlumno:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Instalar PHPUnit con Composer
        run: cd appAlumno; composer require --dev phpunit/phpunit ^7
      - name: Ejecutar pruebas unitarias del Alumno
        run: cd appAlumno; ./vendor/bin/phpunit tests/

  RunUnitTestsDocente:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Instalar PHPUnit con Composer
        run: cd appDocente; composer require --dev phpunit/phpunit ^7
      - name: Ejecutar pruebas unitarias del Docente
        run: cd appDocente; ./vendor/bin/phpunit tests/

  RunUnitTestsAdministrador:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Instalar PHPUnit con Composer
        run: cd appAdmin; composer require --dev phpunit/phpunit ^7
      - name: Ejecutar pruebas unitarias del Administrador
        run: cd appAdmin; ./vendor/bin/phpunit tests/